model:
  n_layers: 7
  hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}
  hidden_dims : {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}
  transition: 'marginal'
  extra_features: 'rrwp'
  rrwp_steps: 12
  checkpoint_path: '../checkpoints/qm9_with_h_conditional.pt'
sample:
  rdb: 'general'
  rdb_crit: dummy
  schedule: 'RR' # We can use FCFS or RR
  quantum: 1
  retry_invalid_graphs: true
